### ISSUE TITLE
Decide upon and set up a database

### ISSUE THREAD

**Issue by stevenlaitran** [build-umass/Gifted_LLC#4]
We need to decide on a database to store the data. I recommend MySQL for local development and Postgres for the remote environment. Both uses the same syntax, but one is more robust. Relational databases are much better to learn for a beginner as well. 

Note: set an instance up and try not connect to it yet see a later story

- [x]  Set up a local instance of the database for the app
- [x]  Set up and test a remote instance of the database

**Comment by vedantroy** [comment]
How do we setup a remote instance of the database? I don't think we have a AWS instance/other server yet.

**Comment by stevenlaitran** [comment]
This story is later down the line, I'll speak with Nilay about setting up a test instance for build, but the most important thing about this story is deciding on what database to use and making sure the database can work locally as well as remotely, factoring in the cost/effectiveness of the technologies used.

**Comment by robtac** [comment]
Looking into Postgres and MySQL, it seems to me that MySQL is better suited for our purposes. They're both free to use (license wise), but Postgres excels in large, complex queries, which isn't really what I see our database being used as. MySQL seems like the more efficient choice for our application.

**Comment by vedantroy** [comment]
I don't think performance will be an issue with either database considering we aren't building a large-scale/high-performance application.

 Postgres has several benefits:
- Excellent documentation
- Has a better/more strict default configuration that prevents people from shooting their own feet?
    - Generally, postgres seems to focus on being "correct". I don't know if this really matters though because MySQL is also very safe/reliable.
- From an educational perspective:
    - Postgres strictly adheres to the SQL standard. This may be valuable because 
    any skills learned with Postgres will translate to other SQL databases.
    - Postgres is rapidly increasing in popularity/being used by more and more startups/companies. 
    Thus, learning Postgres may be a valuable skill.

MySQL's primary benefits are:
- Good master-master replication. I am not sure if we will be replicating our database though.
- Widely used, so there should be a large community online.

It is unclear whether postgres is harder to setup than MySQL. Some people say postgres is easier because of its better defaults and excellent documentation, but others say MySQL is easier.

Ultimately, I think postgres is a good choice because of its excellent documentation and educational value due to its strict adherence to SQL standards. I also think Postgre's focus on "correctness" may be helpful in the long run. However, I don't have a super strong preference in either direction (slightly leaning towards postgres).

**Comment by stevenlaitran** [comment]
implemented (development part) on PR #14
